<?xml version="1.0" encoding="utf-8"?><Database Name="QLSACH" Class="ThuVienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQlExpress;Initial Catalog=QLSACH;Integrated Security=True" SettingsObjectName="QLTV.Properties.Settings" SettingsPropertyName="QLSACHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CuonSach" Member="CuonSaches">
    <Type Name="CuonSach">
      <Column Name="MaSach" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="MaCuon" Type="System.String" DbType="NChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ViTri" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="CuonSach_Muon" Member="Muons" ThisKey="MaCuon" OtherKey="MaCuon" Type="Muon" />
      <Association Name="Dausach_CuonSach" Member="Dausach" ThisKey="MaSach" OtherKey="Masach" Type="Dausach" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TacGia" Member="TacGias">
    <Type Name="TacGia">
      <Column Name="Masach" Type="System.String" DbType="NChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Dausach_TacGia" Member="Dausach" ThisKey="Masach" OtherKey="Masach" Type="Dausach" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Dausach" Member="Dausaches">
    <Type Name="Dausach">
      <Column Name="Masach" Type="System.String" DbType="NChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tua" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaNXB" Type="System.String" DbType="NChar(3) NOT NULL" CanBeNull="false" />
      <Association Name="Dausach_CuonSach" Member="CuonSaches" ThisKey="Masach" OtherKey="MaSach" Type="CuonSach" />
      <Association Name="Dausach_TacGia" Member="TacGias" ThisKey="Masach" OtherKey="Masach" Type="TacGia" />
      <Association Name="NXB_Dausach" Member="NXB" ThisKey="MaNXB" OtherKey="MaNXB" Type="NXB" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocGia" Member="DocGias">
    <Type Name="DocGia">
      <Column Name="MaDG" Type="System.String" DbType="NChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDG" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="SoDT" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="DocGia_Muon" Member="Muons" ThisKey="MaDG" OtherKey="MaDG" Type="Muon" />
    </Type>
  </Table>
  <Table Name="dbo.Muon" Member="Muons">
    <Type Name="Muon">
      <Column Name="MaCuon" Type="System.String" DbType="NChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDG" Type="System.String" DbType="NChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayMuon" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NgayTra" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="CuonSach_Muon" Member="CuonSach" ThisKey="MaCuon" OtherKey="MaCuon" Type="CuonSach" IsForeignKey="true" />
      <Association Name="DocGia_Muon" Member="DocGia" ThisKey="MaDG" OtherKey="MaDG" Type="DocGia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NXB" Member="NXBs">
    <Type Name="NXB">
      <Column Name="MaNXB" Type="System.String" DbType="NChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SoDT" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="NXB_Dausach" Member="Dausaches" ThisKey="MaNXB" OtherKey="MaNXB" Type="Dausach" />
    </Type>
  </Table>
</Database>